# Options to make tmux more pleasant
set -g mouse on
set -g default-command "fish"

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_status_background "#{@thm_bg}"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_host_color "#{@thm_teal}"

set-option -g status-position top
set-option -g focus-events on

# Load catppuccin
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# Make the status line pretty and add some modules
set -g status-left ""

set -g status-right-length 100
set -g status-right "#{E:@catppuccin_status_host}"
set -ag status-right "#{E:@catppuccin_status_session}"

#---- Keybinds ----
# Smart pane switching with awareness of Neovim splits.
bind-key -n M-h if -F "#{@pane-is-vim}" 'send-keys M-h' 'select-pane -L'
bind-key -n M-j if -F "#{@pane-is-vim}" 'send-keys M-j' 'select-pane -D'
bind-key -n M-k if -F "#{@pane-is-vim}" 'send-keys M-k' 'select-pane -U'
bind-key -n M-l if -F "#{@pane-is-vim}" 'send-keys M-l' 'select-pane -R'

# Smart pane resizing with awareness of Neovim splits.
bind-key -n C-Left  if -F "#{@pane-is-vim}" 'send-keys C-Left'  'resize-pane -L 3'
bind-key -n C-Down  if -F "#{@pane-is-vim}" 'send-keys C-Down'  'resize-pane -D 3'
bind-key -n C-Up    if -F "#{@pane-is-vim}" 'send-keys C-Up'    'resize-pane -U 3'
bind-key -n C-Right if -F "#{@pane-is-vim}" 'send-keys C-Right' 'resize-pane -R 3'
